apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-backup
  namespace: devops-tools
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
  claimRef:
    namespace: devops-tools
    name: jenkins-backup